### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by sebastiandres** [tylerjrichards/st-paywall#15]
As the project seems to be growing quickly, the README file soon will be too large to contain all the explanations. 
I would suggest (and volunteer) to create a readthedocs documentation, that is actually not so hard to maintain.
See as an example a previous pet project: https://streamlit-book.readthedocs.io/en/latest/

The documentation should live on the same repo project and get's updated automatically when the main branch of the repo is updated.

Outline:
- Project scope (why)
- Google Auth: requirements, setup, code
- Adding a new authentication to st-paywall
- Payment with Stripe: requirements, setup, code
- Adding a new payment to st-paywall

**Comment by tylerjrichards** [comment]
this is a really great idea, would love to help with a PR on this!

**Comment by sebastiandres** [comment]
OK, I'll fork and setup the documentation files!

**Comment by tylerjrichards** [comment]
closing this as we merged the PR today
