### ISSUE TITLE
when using buymeacoffee, stripe secrets still required

### ISSUE THREAD

**Issue by sfc-gh-trichards** [tylerjrichards/st-paywall#25]
kindly noticed by @abrabyt who was testing this out

**Comment by sfc-gh-trichards** [comment]
![CleanShot 2023-07-31 at 15 38 20@2x](https://github.com/tylerjrichards/st-paywall/assets/103017176/f74caf73-660c-44ae-a9c7-70fe1d0f40b2)

**Comment by tylerjrichards** [comment]
fixing this here: https://github.com/tylerjrichards/st-paywall/pull/28
