### ISSUE TITLE
What if the subscription has expired?

### ISSUE THREAD

**Issue by lihotim** [tylerjrichards/st-paywall#27]
When the subscription has expired, what will the UI behave? Will the user not be able to login the SaaS through his email anymore?

**Comment by sfc-gh-trichards** [comment]
oh this is a really good point, I honestly hadn't thought of that. It looks like the Stripe API has a field for if the subscription is active, let me make a change to update!

**Comment by tylerjrichards** [comment]
fixing this here: https://github.com/tylerjrichards/st-paywall/pull/28

**Comment by tylerjrichards** [comment]
this should be fixed now, let me know if this works for you @lihotim :)
