### ISSUE TITLE
Error message rak_subscription_read’

### ISSUE THREAD

**Issue by roland71** [tylerjrichards/st-paywall#36]
Hello.
I get the following error message:

stripe.error.PermissionError: Request req_lsDZr: The provided key 'rk_test_Cb3gph’ does not have the required permissions for this endpoint on account ‘acct_1NuzflB0DBR1HOyc’. Having the ‘rak_subscription_read’ permission would allow this request to continue.

I don’t find any information about ‘rak_subscription_read’ and what to do now?
Thanks!

**Comment by tylerjrichards** [comment]
hey @roland71, did your issue get fixed?
