### ISSUE TITLE
we should update st.experimental_rerun  to st.rerun

### ISSUE THREAD

**Issue by marcosberghahn** [tylerjrichards/st-paywall#39]
st.experimental_rerun was deprecated in version 1.27.0. Uwe should use st.rerun instead. As decribed on the docs:
https://docs.streamlit.io/library/api-reference/control-flow/st.experimental_rerun

Currently I'm having problems, after a user login (one that already has a subscription) the page is not reloading. I have to press 'R' on the keyboard to load the correct content. I hope this correction might resolve this.

**Comment by sfc-gh-trichards** [comment]
yeah you're right here, sorry about that. Will fix!

**Comment by tylerjrichards** [comment]
https://github.com/tylerjrichards/st-paywall/pull/43 updated
