### ISSUE TITLE
"is_subscriber" doesn't update after user made payment

### ISSUE THREAD

**Issue by michelle-w-br** [tylerjrichards/st-paywall#48]
the variable "is_subscriber" isn't updated after user made payment through stripe, the streamlit app shows "Login with Google" again after user made payment. Anyone else experience the same issue?

**Comment by michelle-w-br** [comment]
seems by nature it was not updated automatically

**Comment by sfc-gh-trichards** [comment]
Hey @michelle-w-br what do you mean? is there a way you'd like it work differently?

**Comment by michelle-w-br** [comment]
I am thinking if it is possible that streamlit will be notified automatically after user made payment. Does the user need to fresh the app page and login again in order to detect if the user has made payment?

**Comment by sfc-gh-trichards** [comment]
oh yes, there is no way for streamlit to "know" that the user has subscribed, we have to make a new api call to Stripe so they'll need to refresh
