### ISSUE TITLE
Query_params warning from st_paywall

### ISSUE THREAD

**Issue by jozkotrapko** [tylerjrichards/st-paywall#54]
While using st_paywall, I receive a warning for query_params. If I’m not mistaken, it seems that [google_auth.py](https://github.com/tylerjrichards/st-paywall/blob/main/src/st_paywall/google_auth.py) is causing this issue, where `st.experimental_get_query_params()` is used. 

![image](https://github.com/tylerjrichards/st-paywall/assets/85027659/00b68957-3e8d-4f86-bc15-7c3c20fd0245)

**Comment by sfc-gh-trichards** [comment]
yes, that is because you're using a newer version of Streamlit! You're probably on 1.30 or 1.31
