### ISSUE TITLE
I need integrate cryptomus -  Could you helP?

### ISSUE THREAD

**Issue by joker096** [tylerjrichards/st-paywall#55]
[cryptomus](https://app.cryptomus.com/signup?ref=nDAej6) - is more convenient for users, who don`t use stripe and bymeacoffee. Almost zero commisions.

**Comment by tylerjrichards** [comment]
hey @joker096, I don't have the bandwidth to help with a cryptomus integration. PRs are welcome but I don't know if st-paywall is a great spot for crypto payments
