### ISSUE TITLE
Please extend this for multi-page Streamlit apps

### ISSUE THREAD

**Issue by rajtilakjee** [tylerjrichards/st-paywall#57]
I tried searching for something that would extend the functionality of st-paywall to a multi-page app but couldn't come up with anything. It would be great if you can arrange for something that would implement this functionality.

**Comment by tylerjrichards** [comment]
hey there, have you tried it with a multipage app? I am pretty sure add_auth() would work out of the box here

**Comment by rajtilakjee** [comment]
I haven't tried it yet. Let me give it a shot first thing tomorrow morning and will let you know. Thank you so much for your reply.
