### ISSUE TITLE
ModuleNotFoundError: No module named 'st_paywall'

### ISSUE THREAD

**Issue by hahnsangkim** [tylerjrichards/st-paywall#60]
These are the steps I took.
1. I cloned the repo 
2. cd st-paywall
3. st-paywall> pip install st-paywall
4. st-paywall> streamlit run streamlit_app.py

I encountered the error "ModuleNotFoundError: No module named 'st_paywall'."
Am I missing anything?

**Comment by hahnsangkim** [comment]
My bad. it was related to an environment I set up. Now, it works fine. I will close this issue.

**Comment by tylerjrichards** [comment]
glad it worked out!
