### ISSUE TITLE
[Feature Request] bitcoin paywall

### ISSUE THREAD

**Issue by PlebeiusGaragicus** [tylerjrichards/st-paywall#62]
Been looking to roll my own solution for this - but a bitcoin paywall would be very useful.  Integrating with Stripe is a non-starter for many and limits self-sovereignty.

Ideally a lightning-based solution would enable users to use a mobile lightning wallet (or browser extension) to easily check for past payments for a given content or allow for one-tap payments.

**Comment by tylerjrichards** [comment]
hey Plebeius, you're welcome to fork and give this a shot! I don't think I care enough about bitcoin / crypto to try and help out here, but if you think it is a good idea then you should definitely go for it :)
