### ISSUE TITLE
Please replace `st.experimental_get_query_params` with `st.query_params`

### ISSUE THREAD

**Issue by tangletips** [tylerjrichards/st-paywall#64]
When using  st-paywall with the current streamlit version (1.33.00) the following error is shown:

Please replace `st.experimental_get_query_params` with `st.query_params`.

`st.experimental_get_query_params` will be removed after 2024-04-11.

https://github.com/tylerjrichards/st-paywall/blob/35dd9b4a29ddf8b704f7abaf14714644292d482a/src/st_paywall/google_auth.py#L84

**Comment by tangletips** [comment]
Just saw now that this is already addressed in the branch `update-streamlit-version`  and PR  #61

**Comment by LouisDeconinck** [comment]
@tylerjrichards Can PR #61 be merged? This quite literally breaks the entire application.

**Comment by kajfadjfaf8er3js2** [comment]
> @tylerjrichards Can PR #61 be merged? This quite literally breaks the entire application.

second this. Please can we fix.

**Comment by tylerjrichards** [comment]
hey I just went ahead and fixed this in version 0.1.7, will you all let me know how that works for you? https://pypi.org/project/st-paywall/0.1.7/
